import { randomUUID } from 'crypto';

const ERP_API_URL = process.env.ERP_API_URL || 'https://erp.prepoc.in';
const ERP_API_VERSION = process.env.ERP_API_VERSION || 'v1';
const BASE_URL = `${ERP_API_URL}/api/${ERP_API_VERSION}/public/recruitment`;

// Standard response from ERP
export interface ERPResponse<T = any> {
  success: boolean;
  data: T | null;
  meta: any | null;
  error: {
    code: string;
    message: string;
    details?: any;
  } | null;
}

const generateCorrelationId = () => {
  return typeof randomUUID === 'function' ? randomUUID() : Math.random().toString(36).substring(2);
};

const getHeaders = () => {
  return {
    'Accept': 'application/json',
    'X-Correlation-ID': generateCorrelationId(),
  };
};

const withRetry = async <T>(fetchFn: () => Promise<Response>, retries = 2, delayMs = 1000): Promise<Response> => {
  try {
    const res = await fetchFn();
    if (!res.ok && res.status >= 500 && retries > 0) {
      throw new Error(`Server error ${res.status}`);
    }
    return res;
  } catch (error) {
    if (retries > 0) {
      console.warn(`ERP API request failed. Retrying in ${delayMs}ms... (${retries} retries left)`);
      await new Promise(resolve => setTimeout(resolve, delayMs));
      return withRetry(fetchFn, retries - 1, delayMs * 2);
    }
    throw error;
  }
};

const handleResponse = async <T>(response: Response): Promise<ERPResponse<T>> => {
  if (!response.ok && response.status >= 500) {
    return {
      success: false,
      data: null,
      meta: null,
      error: {
        code: 'ERP_UNAVAILABLE',
        message: "We're temporarily unable to accept applications. Please try again shortly."
      }
    };
  }
  
  try {
    const data = await response.json();
    // If the backend returned our standard format
    if (data && typeof data === 'object' && 'success' in data) {
      return data as ERPResponse<T>;
    }
    
    // Fallback if ERP returned something else (shouldn't happen with our StandardResponseRenderer)
    return {
      success: response.ok,
      data: response.ok ? data : null,
      meta: null,
      error: response.ok ? null : {
        code: 'UNKNOWN_ERROR',
        message: data.detail || 'An unexpected error occurred.'
      }
    };
  } catch (err) {
    return {
      success: false,
      data: null,
      meta: null,
      error: {
        code: 'PARSE_ERROR',
        message: 'Invalid response from server.'
      }
    };
  }
};

export const erpApi = {
  getJobs: async (params?: Record<string, string>) => {
    const searchParams = new URLSearchParams(params);
    const qs = searchParams.toString();
    const url = `${BASE_URL}/jobs/${qs ? '?' + qs : ''}`;
    
    try {
      const response = await withRetry(() => fetch(url, {
        method: 'GET',
        headers: getHeaders(),
        next: { revalidate: 300 } // Cache for 5 minutes
      }));
      return handleResponse<any>(response);
    } catch (e) {
      return handleResponse<any>(new Response(null, { status: 503 }));
    }
  },

  getFeaturedJobs: async () => {
    try {
      const response = await withRetry(() => fetch(`${BASE_URL}/jobs/featured/`, {
        method: 'GET',
        headers: getHeaders(),
        next: { revalidate: 300 }
      }));
      return handleResponse<any>(response);
    } catch (e) {
      return handleResponse<any>(new Response(null, { status: 503 }));
    }
  },

  getJob: async (slug: string) => {
    try {
      const response = await withRetry(() => fetch(`${BASE_URL}/jobs/${slug}/`, {
        method: 'GET',
        headers: getHeaders(),
        next: { revalidate: 1800 } // Cache for 30 minutes
      }));
      return handleResponse<any>(response);
    } catch (e) {
      return handleResponse<any>(new Response(null, { status: 503 }));
    }
  },

  getMeta: async () => {
    try {
      const response = await withRetry(() => fetch(`${BASE_URL}/meta/`, {
        method: 'GET',
        headers: getHeaders(),
        next: { revalidate: 3600 } // Cache for 1 hour
      }));
      return handleResponse<any>(response);
    } catch (e) {
      return handleResponse<any>(new Response(null, { status: 503 }));
    }
  },
  
  checkHealth: async () => {
    try {
      const response = await fetch(`${BASE_URL}/health/`, {
        method: 'GET',
        headers: getHeaders(),
        next: { revalidate: 60 }
      });
      return response.ok;
    } catch (e) {
      return false;
    }
  },

  applyForJob: async (slug: string, formData: FormData) => {
    try {
      const headers = getHeaders();
      // Remove Accept for file upload to allow multipart boundary to be generated by fetch automatically
      
      const response = await fetch(`${BASE_URL}/jobs/${slug}/apply/`, {
        method: 'POST',
        headers: {
          'X-Correlation-ID': headers['X-Correlation-ID']
        },
        body: formData,
        cache: 'no-store'
      });
      return handleResponse<any>(response);
    } catch (e) {
      return handleResponse<any>(new Response(null, { status: 503 }));
    }
  }
};
